services:
  placepix:
    build: .
    container_name: placepix
    ports:
      - "3000:3000"
    volumes:
      - ./images:/app/images
      - ./.cache:/app/.cache
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
